layout_spectrum: 0.2634408
typography_spectrum: 0.8100358
color:
  saturation: 1
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 0.2777778
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: mhairer
